name: Pull Request
description: Raise a Pull Request for ECI Terraform Modules
labels: ["bug-fixes", "enhancement-delivery", "feature-delivery"]
body:
  - type: textarea
    attributes:
      label: PR Description
      description: Describe what the PR does/fixes clearly and concisely.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Special Notes for Reviewers, if any
      description: Provide any additional notes you want to leave for the reviewers, like delivers a part of a feature/enhancement, .
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Is latest workflow run successful?
      description: Check if latest workflow run for the latest commit in the PR was successful and all stages ran properly. 
    options:
      required: true
  - type: checkboxes
    attributes:
      label: Bumped terraform module version?
      description: Check if all modified terraform module(s) have their versions bumped in its terraform.yaml file.
    options:
      required: true
  - type: checkboxes
    attributes:
      label: GitHub/Jira/ServiceDesk Issue link is attached to PR
      description: Check if issue link from GitHub/Jira/ServiceDesk is attached to the PR 
    options:
      required: false
  - type: checkboxes
    attributes:
      label: This PR contains documentation
      description: Check if documentation link or README is added in PR for the change done 
    options:
      required: false